import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Shared/Layout'
import Hero from '../components/Pages/Home/Hero/Hero'
import FeaturedPosts from '../components/Pages/Home/FeaturedPosts/FeaturedPosts'
import Banner from '../components/Pages/Home/Banner/Banner'


export default function Home() {
  return (
    <>
      <Head>
        <title>The Gisthiv</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout className="landing">
        <Hero />
        <FeaturedPosts />
        <Banner />
      </Layout>
    </>
  )
}
