import Link from 'next/link'
import { Container, Row, Col, Card } from 'react-bootstrap'



const data = [
    {
        _id: 'DF445',
        img: '/img/f0.jpg',
        category: 'Physics',
        title: 'Physicists Edge Closer to Taming the Three-Body Problem',
        excerpt: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
    },
    {
        _id: 'DF446',
        img: '/img/f1.jpg',
        category: 'Insect',
        title: 'New pumpkin toadlet species found—and it secretly glows in the dark',
        excerpt: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
    },
    {
        _id: 'DF486',
        img: '/img/f2.jpg',
        category: 'Chemistry',
        title: 'How well can molecules be generated by AI?',
        excerpt: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
    },
    {
        _id: 'DF466',
        img: '/img/f3.jpg',
        category: 'Medical',
        title: 'Retrospectively registered trials: the Editors’ dilemma',
        excerpt: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
    },
]

const ResearchArticles = () => {
    return (
        <>
            <section>
                <div className="--s-header">
                    <Container>
                        <h2 className="--s-title">RESEARCH ARTICLES</h2>
                    </Container>
                </div>

                <div className="--s-body">
                    <Container>
                        <Row>
                            <Col lg={12} md={12} ms={12}>
                                {data?.map(item => (
                                    <Card key={item._id} className="gh-card-full-width">
                                        
                                        <Card.Body>
                                            <Row className="no-wrap">
                                                <Col lg={9} md={9} sm={8}>
                                                    <Row>
                                                        <Col lg={3} md={3} sm={12}>
                                                            <Card.Subtitle className="--card-cat"><span>{ item.category }</span></Card.Subtitle>
                                                            <Card.Text className="--card-date">23 Feb 2021</Card.Text>
                                                        </Col>
                                                        <Col lg={9} md={9} sm={12}>
                                                            <Card.Title>{ item.title }</Card.Title>
                                                            <Card.Text className="--card-excerpt">{item.excerpt}</Card.Text>
                                                            
                                                            <Card.Text className="--card-author">Ivana Yen, Frances Shanahan, Shiva Malek</Card.Text>
                                                        </Col>
                                                    </Row>
                                                </Col>

                                                <Col lg={3} md={3} sm={4}>
                                                    <Card.Img src={item.img} />
                                                </Col>
                                            </Row>
                                        </Card.Body>
                                    </Card>
                                ))}
                            </Col>
                        </Row>
                    </Container>
                </div>
            </section>
        </>
    )
}

export default ResearchArticles
