import Link from 'next/link'
import { Card, Col, Container, Row } from 'react-bootstrap'


const data = [
    {
        _id: 'DF445',
        img: '/img/f0.jpg',
        category: 'Physics',
        title: 'Physicists Edge Closer to Taming the Three-Body Problem',
        excerpt: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
    },
    {
        _id: 'DF446',
        img: '/img/f1.jpg',
        category: 'Insect',
        title: 'New pumpkin toadlet species found—and it secretly glows in the dark',
        excerpt: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
    },
    {
        _id: 'DF486',
        img: '/img/f2.jpg',
        category: 'Chemistry',
        title: 'How well can molecules be generated by AI?',
        excerpt: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
    },
    {
        _id: 'DF466',
        img: '/img/f3.jpg',
        category: 'Medical',
        title: 'Retrospectively registered trials: the Editors’ dilemma',
        excerpt: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
    },
]

const FeaturedPosts = () => {
    return (
        <>
            <section className="gh-s-featured-post">
                <Container>
                    <Row>
                        {data?.map(item => (
                            <Col lg={3} md={3} sm={12} key={item._id}>
                                <Link href={`/article/${item._id}`}>
                                    <a className="gh-card">
                                        <Card className="mb-4">
                                            <Card.Img src={item.img} />

                                            <Card.Body>
                                                <Card.Subtitle className="text-muted">{item.category}</Card.Subtitle>
                                                <Card.Title>{item.title}</Card.Title>
                                                <Card.Text>{item.excerpt}</Card.Text>
                                            </Card.Body>
                                        </Card>
                                    </a>
                                </Link>
                            </Col>
                        ))}
                        
                    </Row>
                </Container>
            </section>
        </>
    )
}

export default FeaturedPosts
